Traceback (most recent call last):
  File "manager_main.py", line 13, in <module>
IOError: [Errno 2] No such file or directory: 'E:\\workspace\\jorhy-ud\\canteen\\dist\\library.zip\\config.json'
Traceback (most recent call last):
  File "manager_main.py", line 13, in <module>
IOError: [Errno 2] No such file or directory: 'E:\\workspace\\jorhy-ud\\canteen\\dist\\library.zip\\config.json'
Traceback (most recent call last):
  File "manager_main.py", line 13, in <module>
IOError: [Errno 2] No such file or directory: 'E:\\workspace\\jorhy-ud\\canteen\\dist\\library.zip\\..\\config.json'
Traceback (most recent call last):
  File "app\manager\UI\kitchen_printer.pyc", line 291, in on_btn_save
  File "app\manager\logic\ctrl.pyc", line 727, in add_item
  File "service\data_base\manager.pyc", line 179, in add_item
  File "sqlalchemy\orm\session.pyc", line 1919, in flush
  File "sqlalchemy\orm\session.pyc", line 2037, in _flush
  File "sqlalchemy\util\langhelpers.pyc", line 60, in __exit__
  File "sqlalchemy\orm\session.pyc", line 2001, in _flush
  File "sqlalchemy\orm\unitofwork.pyc", line 372, in execute
  File "sqlalchemy\orm\unitofwork.pyc", line 526, in execute
  File "sqlalchemy\orm\persistence.pyc", line 65, in save_obj
  File "sqlalchemy\orm\persistence.pyc", line 602, in _emit_insert_statements
  File "sqlalchemy\engine\base.pyc", line 729, in execute
  File "sqlalchemy\sql\elements.pyc", line 321, in _execute_on_connection
  File "sqlalchemy\engine\base.pyc", line 826, in _execute_clauseelement
  File "sqlalchemy\engine\base.pyc", line 958, in _execute_context
  File "sqlalchemy\engine\base.pyc", line 1160, in _handle_dbapi_exception
  File "sqlalchemy\util\compat.pyc", line 199, in raise_from_cause
  File "sqlalchemy\engine\base.pyc", line 951, in _execute_context
  File "sqlalchemy\engine\default.pyc", line 436, in do_execute
  File "MySQLdb\cursors.pyc", line 205, in execute
  File "MySQLdb\connections.pyc", line 36, in defaulterrorhandler
sqlalchemy.exc.IntegrityError: (IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`canteen`.`printer_scheme`, CONSTRAINT `num_backup_scheme_id` FOREIGN KEY (`num_backup_scheme_id`) REFERENCES `printer_scheme` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)') 'INSERT INTO printer_scheme (vch_name, num_valid, num_scheme_type, num_print_count, num_backup_scheme_id, vch_code) VALUES (%s, %s, %s, %s, %s, %s)' (u'1', True, 1, 1, 0, u'1')
Traceback (most recent call last):
  File "app\manager\UI\kitchen_printer.pyc", line 840, in on_btn_refresh
  File "app\manager\UI\kitchen_printer.pyc", line 781, in _refresh_ui
  File "app\manager\logic\ctrl.pyc", line 714, in refresh_items
  File "service\data_base\manager.pyc", line 39, in get_all
  File "sqlalchemy\orm\session.pyc", line 776, in commit
  File "sqlalchemy\orm\session.pyc", line 375, in commit
  File "sqlalchemy\orm\session.pyc", line 214, in _assert_active
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`canteen`.`printer_scheme`, CONSTRAINT `num_backup_scheme_id` FOREIGN KEY (`num_backup_scheme_id`) REFERENCES `printer_scheme` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)') 'INSERT INTO printer_scheme (vch_name, num_valid, num_scheme_type, num_print_count, num_backup_scheme_id, vch_code) VALUES (%s, %s, %s, %s, %s, %s)' (u'1', True, 1, 1, 0, u'1')
Traceback (most recent call last):
  File "app\manager\UI\kitchen_printer.pyc", line 807, in on_btn_new
  File "app\manager\UI\kitchen_printer.pyc", line 196, in __init__
  File "app\manager\UI\kitchen_printer.pyc", line 206, in _initialize_view
  File "app\manager\UI\kitchen_printer.pyc", line 212, in _init_add_view
  File "app\manager\logic\ctrl.pyc", line 755, in get_data
  File "service\data_base\manager.pyc", line 39, in get_all
  File "sqlalchemy\orm\session.pyc", line 776, in commit
  File "sqlalchemy\orm\session.pyc", line 375, in commit
  File "sqlalchemy\orm\session.pyc", line 214, in _assert_active
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`canteen`.`printer_scheme`, CONSTRAINT `num_backup_scheme_id` FOREIGN KEY (`num_backup_scheme_id`) REFERENCES `printer_scheme` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)') 'INSERT INTO printer_scheme (vch_name, num_valid, num_scheme_type, num_print_count, num_backup_scheme_id, vch_code) VALUES (%s, %s, %s, %s, %s, %s)' (u'1', True, 1, 1, 0, u'1')
Traceback (most recent call last):
  File "app\manager\UI\kitchen_printer.pyc", line 807, in on_btn_new
  File "app\manager\UI\kitchen_printer.pyc", line 196, in __init__
  File "app\manager\UI\kitchen_printer.pyc", line 206, in _initialize_view
  File "app\manager\UI\kitchen_printer.pyc", line 212, in _init_add_view
  File "app\manager\logic\ctrl.pyc", line 755, in get_data
  File "service\data_base\manager.pyc", line 39, in get_all
  File "sqlalchemy\orm\session.pyc", line 776, in commit
  File "sqlalchemy\orm\session.pyc", line 375, in commit
  File "sqlalchemy\orm\session.pyc", line 214, in _assert_active
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`canteen`.`printer_scheme`, CONSTRAINT `num_backup_scheme_id` FOREIGN KEY (`num_backup_scheme_id`) REFERENCES `printer_scheme` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)') 'INSERT INTO printer_scheme (vch_name, num_valid, num_scheme_type, num_print_count, num_backup_scheme_id, vch_code) VALUES (%s, %s, %s, %s, %s, %s)' (u'1', True, 1, 1, 0, u'1')
